export enum Screens {
  HOME = 'HOME',
  NEW_POCKET_NAME = 'NEW_POCKET_NAME',
  NEW_POCKET_INITIAL_VALUE = 'NEW_POCKET_INITIAL_VALUE',
  NEW_POCKET_GOAL = 'NEW_POCKET_GOAL',
  POCKET_DETAILS = 'POCKET_DETAILS',
  POCKET_EDIT = 'POCKET_EDIT',
}